spring:
  application:
    name: log-monitor

  datasource:
    url: jdbc:postgresql://localhost:5432/log_monitor
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      fetch-min-size: 50000
      fetch-max-wait: 500
      group-id: log-monitor-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "io.github.hyuna.logmonitor.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
    listener:
      type: batch
      concurrency: 3
cache:
  type: redis
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081